[project]

name = "Initial Rollout of TCP"
platform = "firefox_desktop"
alerts = [
    "ci_diffs",
    "crash_tresholds",
    "memory_thresholds",
    "hist_diff"
]
metrics = [
    'tab_unload_count',
    'tab_reload_count',
    'tab_unload_to_reload',
    'checkerboard_severity',
    'child_process_launch_ms',
    'content_frame_time_vsync',
    'content_process_max',
    'cycle_collector_max_pause',
    'cycle_collector_max_pause_content',
    'fx_new_window_ms',
    'fx_tab_switch_composite_e10s_ms',
    'gc_budget_overrun',
    'gc_mark_rate_2',
    'gc_reason_2',
    'gc_max_pause_2',
    'gc_max_pause_2_content',
    'gc_ms',
    'gc_ms_content',
    'gc_non_incremental',
    'gc_slice_during_idle',
    'gc_slice_during_idle_content'
]
reference_branch = "disabled"

[project.population]

data_source = "main"

[alerts]

[alerts.ci_diffs]
type = "ci_overlap"
metrics = [
    "gc_ms",
    "content_crashes",
    "main_crashes",
    "startup_crashes",
]
parameters = [50, 90]
statistics = ["percentile"]

[alerts.crash_tresholds]
type = "threshold"
metrics = [
    "content_crashes",
    "shutdown_hangs",
    "oom_crashes",
    "gpu_crashes"
]
parameters = [50, 90]
min = [0, 0]
max = [0, 1]

[alerts.memory_thresholds]
type = "threshold"
metrics = [
    "memory_total"
]
parameters = [50, 90]
min = [0, 0]
max = [500000, 850000]

[alerts.hist_diff]
type = "avg_diff"
metrics = [
    "memory_total",
    "oom_crashes",
    "main_crashes"
]
window_size = 7
max_relative_change = 0.5
parameters = [50, 90]
