[project]

name = "Initial Rollout of TCP"
platform = "firefox_desktop"
alerts = [
    "ci_diffs",
    "crash_tresholds",
    "memory_thresholds",
    "hist_diff"
]
metrics = [
    'tab_unload_count',
    'tab_reload_count'
]
reference_branch = "disabled"

[project.population]

data_source = "main"

[alerts]

[alerts.ci_diffs]
type = "ci_overlap"
metrics = [
    "gc_ms",
    "content_crashes",
    "main_crashes",
    "startup_crashes",
]
parameters = [50, 90]
statistics = ["percentile"]

[alerts.crash_tresholds]
type = "threshold"
metrics = [
    "content_crashes",
    "shutdown_hangs",
    "oom_crashes",
    "gpu_crashes"
]
parameters = [50, 90]
min = [0, 0]
max = [0, 1]

[alerts.memory_thresholds]
type = "threshold"
metrics = [
    "memory_total"
]
parameters = [50, 90]
min = [0, 0]
max = [500000, 850000]

[alerts.hist_diff]
type = "avg_diff"
metrics = [
    "memory_total",
    "oom_crashes",
    "main_crashes"
]
window_size = 7
max_relative_change = 0.5
parameters = [50, 90]
