[project]

name = "Mission Control Desktop Nightly"
platform = "firefox_desktop"
xaxis = "submission_date"
start_date = "2022-03-01"
metrics = [
    'gc_ms',
    'main_crashes',
    'oom_crashes',
]

[project.population]

data_source = "main"
monitor_entire_population = true
dimensions = ["os"]
channel = "nightly"

[data_sources]

[data_sources.main]
from_expression = "mozdata.telemetry.main_nightly"
submission_date_column = "DATE(submission_timestamp)"
