[project]

name = "Mission Control Desktop Nightly"
platform = "firefox_desktop"
xaxis = "submission_date"
start_date = "2022-03-01"
probes = [
    'fx_tab_switch_composite_e10s_ms',
    'gc_ms',
    'main_crashes',
    'oom_crashes',
]

[project.population]

data_source = "main"
monitor_entire_population = true
dimensions = ["build", "os"]
channel = "nightly"
group_by_dimension = "build"

[data_sources]

[data_sources.main]
from_expression = "mozdata.telemetry.main_nightly"
submission_date_column = "DATE(submission_timestamp)"
