[project]

name = "TCP Rollout Phase 2"
platform = "firefox_desktop"
xaxis = "submission_date"
start_date = "2022-06-08"
end_date = "2022-08-30"

probes = [
    "tagged_search_count",
    "tagged_follow_on_search_count",
    "search_with_ads",
    "ad_click",
    "organic_search_count",
    "sap",
    "ad_click_organic",
    "search_with_ads_organic"
]

[project.population]

data_source = "tcp_rollout_main"
branches = [
    "enabled",
    "disabled"
]
dimensions = ["os", "country"]
monitor_entire_population = true


[data_sources]

[data_sources.tcp_rollout_main]
from_expression = """
    (
        WITH clients_per_branch AS (
            SELECT 
                client_id,
                sample_id,
                DATE(submission_timestamp) AS submission_date,
                application.build_id AS build_id,
                normalized_channel,
                normalized_os,
                normalized_country_code,
                CASE payload.processes.parent.scalars.privacy_dfpi_rollout_tcp_by_default_feature 
                    WHEN TRUE THEN "enabled"
                    ELSE "disabled"
                END AS branch
            FROM `moz-fx-data-shared-prod.telemetry.main`,
                UNNEST(environment.experiments) AS experiment
            WHERE 
                (normalized_channel = "release" OR normalized_channel = "beta") AND
                experiment.key IN (
                    "total-cookie-protection-beta-roll-out-phase-ii-switch-on-to-new-users", 
                    "total-cookie-protection-roll-out-to-users-phase-ii-switch-on-by-default"
                )
        )
        SELECT 
        client_id,
        submission_date,
        build_id,
        normalized_channel,
        normalized_os,
        normalized_country_code,
        STRUCT (    -- this is the structure opmon expects
            [
            STRUCT (
                "tcp-rollout-phase-2" AS key,   -- dummy experiment/rollout slug to make opmon happy
                STRUCT(branch AS branch) AS value
            )
            ] AS experiments
        ) AS environment
        FROM clients_per_branch 
        WHERE branch IS NOT NULL
    )
"""
submission_date_column = "submission_date"
build_id_column = "build_id"
