[project]

name = "Telemetry Alerts Prototype"
platform = "firefox_desktop"
xaxis = "submission_date"
start_date = "2022-06-01"
probes = [
    "checkerboard_severity",
    "gc_ms",
    "main_crashes",
    "oom_crashes",
]

[project.population]

data_source = "main"
monitor_entire_population = true
dimensions = ["build", "os"]
channel = "nightly"

[data_sources]

[data_sources.main]
from_expression = "mozdata.telemetry.main_nightly"
submission_date_column = "DATE(submission_timestamp)"

[alerts]

[alerts.hist_diff]
type = "avg_diff"
probes = [
    "checkerboard_severity",
    "gc_ms",
    "main_crashes",
    "oom_crashes",
]
window_size = 7
max_relative_change = 0.5
percentiles = [50]
