version: 2.1

jobs:
  validate:
    docker:
    - image: gcr.io/moz-fx-data-experiments/opmon:latest
    environment:
      BASE_COMMIT: << pipeline.git.base_revision >>
      REVISION_COMMIT: << pipeline.git.revision >>
    steps:
    - checkout
    - run:
        name: Validate config files
        command: |
          changed_files=$(git diff --name-only $BASE_COMMIT..$REVISION_COMMIT -- '*.toml' '*.toml.example')
          echo "Run validation on changed files: "
          echo $changed_files
          opmon validate_config $changed_files
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
