[project]

platform = "firefox_desktop"
xaxis = "submission_date"
metrics = [
    'content_crashes',
    'shutdown_hangs',
    'oom_crashes',
    'main_crashes',
    'startup_crashes'
]

[project.population]

data_source = "main"
