[project]

xaxis = "submission_date"
probes = [
    'content_crashes',
    'shutdown_hangs',
    'oom_crashes',
    'main_crashes',
    'startup_crashes',
    'gc_ms',
    'memory_total'
]

[project.population]

data_source = "main"
branches = ["active"]
