[metrics]

[metrics.uri_count.statistics]
percentile = {}


[metrics.user_reports_site_issue_count.statistics]
percentile = {}
sum = {}


[metrics.user_reload_count.statistics]
percentile = {}
sum = {}


[metrics.baseline_ping_count.statistics]
sum = {}


[metrics.metric_ping_count.statistics]
sum = {}

