name: Auto approve

on: pull_request_target

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.workflows }}
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          workflows:
            - 'defaults/**'
    # run only if 'defaults' files were changed
    - name: workflow tests
      if: steps.filter.outputs.defaults == 'true'
      run: echo "Workflow file"

  approve:
    runs-on: ubuntu-latest
    needs: paths-filter
    permissions:
      pull-requests: write
    if: needs.paths-filter.outputs.defaults == 'true'
    steps:
      - uses: hmarr/auto-approve-action@v3
