name: "Auto approve"
on:
  pull_request:
    branches:
      - main

jobs:
  changed:
    runs-on: ubuntu-latest 
    name: Test changed-files
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2 
      - name: Get changed files in the definitions folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: definitions/*.toml
      outputs:
        changed_files: ${{ steps.changed-files-specific.outputs.all_changed_files }}

  approve:
    name: Run step if any file(s) change
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest 
    needs: changed
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: "APPROVE"
            })
